name: Deploy github pages
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: pnpm/action-setup@v2.1.0
        with:
          run_install: true
      - run: |
              pnpm build
              cd dist
              git config --global user.email "CI@users.noreply.github.com"
              git config --global user.name "CI"
              git init
              git add -A
              git commit -m "deploy"
              git push -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master:gh-pages
